spring.application.name=vetcare
spring.datasource.url=jdbc:postgresql://localhost:5432/VetCare
spring.datasource.username=postgres
spring.datasource.password=04789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true